// NOiNA channel CMS — factory default project list (source of truth for seeding the CMS).
// Channel numbers are derived from list order by the CMS, not stored here.
window.NOINA_PROJECTS_DEFAULT = [
  {label:'PRIME TIME', title:'Knesset TV', sub:'Channel Package', type:'project', aspect:'16/9', vimeoId:'477640753', vimeoUrl:'https://vimeo.com/477640753?share=copy&fl=sv&fe=ci',
    desc:'I got the opportunity to design and animate for The Israeli parliament channel rebrand, after promotheus took part in designing the winning bid. With the new "kaf"/Knesset-plenary-hall logo design and the objective of making the Knesset feel more digital and connected in mind, I\'ve worked on the news broadcast package, multiple shows intros and other knick knacks.'},
  {label:'PRIME TIME', title:'Channel 10', sub:'TV Show Intro', type:'project', aspect:'16/9', vimeoId:'476829578', vimeoUrl:'https://vimeo.com/476829578?share=copy&fl=sv&fe=ci',
    desc:'An opening title sequence I made for the second season of the Israeli sitcom, "Fallen Hard". The bourgeoisie life is tumbling down!'},
  {label:'PRIME TIME', title:'Aiways', sub:'ID Video', type:'project', aspect:'16/9', vimeoId:'688440815', vimeoUrl:'https://vimeo.com/688440815?share=copy&fl=sv&fe=ci',
    desc:"A short ID for Aiways, a chinese electric car manufacturer. It was fun experimenting with reaction diffusion simulation for the first time! I can't wait to mess around with it again."},
  {label:'PRIME TIME', title:'WRC', sub:'2017 Showreel', type:'project', aspect:'16/9', vimeoId:'476837478', vimeoUrl:'https://vimeo.com/476837478?share=copy&fl=sv&fe=ci',
    desc:"A little taste of the World Rally Championship rebrand we did in Promotheus, from real-time TV graphics & dynamic maps to social media integration and technical implementation. I was incharge of the motion theory, intros, bumpers, and other elements of the brand's tv & social package."},
  {label:'PRIME TIME', title:'PayBox', sub:'Commercials', type:'project', aspect:'16/9', vimeoId:'477184602', vimeoUrl:'https://vimeo.com/477184602?share=copy&fl=sv&fe=ci',
    desc:"Promotional campaign for PayBox, a digital wallet and payment app, for TV and numerous social platforms. We had about 3 days per video - pretty stressful, but I'm happy with the end results."},
  {label:'PRIME TIME', title:'Kan Kids', sub:'TV Show Intro', type:'project', aspect:'16/9', vimeoId:'477141864', vimeoUrl:'https://vimeo.com/477141864?share=copy&fl=sv&fe=ci',
    desc:'Opening sequence for a TV show package for "The Bumper-Sticker Poetry" on Kan Educational channel. A series of 10 minutes shorts, each one on the history and background of one iconic bumper-sticker.'},
  {label:'PRIME TIME', title:'Xealth', sub:'Promotional Video', type:'project', aspect:'16/9', vimeoId:'688447594', vimeoUrl:'https://vimeo.com/688447594?share=copy&fl=sv&fe=ci',
    desc:'Promotional video for Xealth, a digital ordering and analytics platform for health vendors.'},
  {label:'PRIME TIME', title:'Vimeo', sub:'2024 Recap', type:'project', aspect:'16/9', vimeoId:'1104693622', vimeoUrl:'https://vimeo.com/1104693622?share=copy&fl=sv&fe=ci',
    desc:'A kind of showreel video, recapping all the standout projects I worked on in 2024 as part of the product creative team. Endless projects across a variety of content worlds, each with its own unique design and animation challenges.'},
  {label:'PRIME TIME', title:'Discount', sub:'Product Teaser Video', type:'project', aspect:'16/9', vimeoId:'476804797', vimeoUrl:'https://vimeo.com/476804797?share=copy&fl=sv&fe=ci',
    desc:'Explainer video for Israel Bank Discount\'s Open Banking platform, for promoting innovation and new financial services using API and other stuff that are beyond my understanding.'},
  {label:'PRIME TIME', title:'Kan 11', sub:'Promo Kit', type:'project', aspect:'16/9', vimeoId:'688422750', vimeoUrl:'https://vimeo.com/688422750?share=copy&fl=sv&fe=ci',
    desc:'Graphic promo kit for Kan\'s TV show "We\'ll meet again" about five secular people whose one of his/her family members have repented and are sent on a journey documenting the attempt to reconnect with that family member. Suuuper emotional.'},
  {label:'PRIME TIME', title:'Bizzabo', sub:'Feature Announcement', type:'project', aspect:'16/9', vimeoId:'689180114', vimeoUrl:'https://vimeo.com/689180114?share=copy&fl=sv&fe=ci',
    desc:"A video introducing Bizzabo's (an event experience OS) brand new app market. It was fun and exciting taking their latest rebrand and bringing it to life with movement and animation."},
  {label:'PRIME TIME', title:'Vimeo', sub:'ProdCon 2024 Intro', type:'project', aspect:'16/9', vimeoId:'1104693380', vimeoUrl:'https://vimeo.com/1104693380?share=copy&fl=sv&fe=ci',
    desc:"An intro video for Vimeo's 2024 product conference in Miami. It was a blast creating a product-focused animation using Vimeo's design language, with a splash of Miami sunshine throughout."},
  {label:'PRIME TIME', title:'yes', sub:'Broadcast graphic package reel', type:'project', aspect:'16/9', vimeoId:'688429066', vimeoUrl:'https://vimeo.com/688429066?share=copy&fl=sv&fe=ci',
    desc:"An onscreen graphic package for yes, a direct broadcast satellite television provider in Israel. This brand design puts the content front and center across all of yes's home channels and digital platforms, from TV shows to movies, with a light cinematic flair. *⁂((✪⥎✪))⁂*"},
  {label:'PRIME TIME', title:'Rak BeHatzbaa', sub:'Kids TV title sequence', type:'project', aspect:'16/9', vimeoId:'477198214', vimeoUrl:'https://vimeo.com/477198214?share=copy&fl=sv&fe=ci',
    desc:'The results are in! An opening title sequence from a full graphic package made for "Only by Vote", a kids TV show on Kan Educational channel about what today\'s kids really think, with fun surveys & polls. The package includes on-screen titles, supers, wipers, a timer and the polls themselves, integrated with Arti\'s AR studio.'},
  {label:'PRIME TIME', title:'Kido', sub:'Agency sizzle reel', type:'project', aspect:'16/9', vimeoId:'1104142278', vimeoUrl:'https://vimeo.com/1104142278?share=copy&fl=sv&fe=ci',
    desc:"A sizzle video showcasing Kido's amazing and innovative projects. I absolutely loved my short time at Kido — thoughtful, seasoned design thinking leading to beautiful projects, all created by genuinely sweet people. ⸜(｡˃ ᵕ ˂ )⸝♡"},
  {label:'PRIME TIME', title:'Folo', sub:'KidsTV diary app', type:'project', aspect:'16/9', vimeoId:'477155128', vimeoUrl:'https://vimeo.com/477155128?share=copy&fl=sv&fe=ci',
    desc:"Meet Folo - the next generation of student diaries! A video I made for the app I designed for Kidstv. Had fun designing a complete app from scratch for the first time (grueling yet rewarding!), but nothing beats animating this wee fella. ɷ◡ɷ"},
  {label:'PRIME TIME', title:'Noder', sub:'Wedding vows film', type:'project', aspect:'16/9', vimeoId:'841602064', vimeoUrl:'https://vimeo.com/841602064?share=copy&fl=sv&fe=ci',
    desc:"For my and my partner's decade celebrations weddingish event, I decided to present my vows with a video, instead of reciting them with a shaky voice & sweaty palms. The color scheme of the entire event was inspired by my partner's favorite arcade game Pac-Man, and I had a blast experimenting with different animation techniques and design trends. That was the most passionate passion project I've had in a long time. Love you, Ba'alulu! ( ˘ ³˘)♥"},
];
